from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

class Migration(migrations.Migration):
    initial=True
    dependencies=[('auth','0012_alter_user_first_name_max_length')]
    operations=[
        migrations.CreateModel(name='Profile',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('display_name',models.CharField(blank=True,max_length=80)),('bio',models.TextField(blank=True,max_length=160)),('avatar',models.ImageField(blank=True,null=True,upload_to='avatars/')),('website',models.URLField(blank=True)),('created_at',models.DateTimeField(auto_now_add=True)),('user',models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name='profile',to='auth.user'))]),
        migrations.CreateModel(name='Post',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('caption',models.TextField(blank=True,max_length=2200)),('image',models.ImageField(blank=True,null=True,upload_to='posts/')),('created_at',models.DateTimeField(auto_now_add=True)),('author',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='posts',to='auth.user'))],options={'ordering':['-created_at']}),
        migrations.CreateModel(name='Story',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('image',models.ImageField(blank=True,null=True,upload_to='stories/images/')),('video',models.FileField(blank=True,null=True,upload_to='stories/videos/')),('caption',models.CharField(blank=True,max_length=220)),('created_at',models.DateTimeField(auto_now_add=True)),('expires_at',models.DateTimeField()),('author',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='stories',to='auth.user'))],options={'ordering':['-created_at']}),
        migrations.CreateModel(name='Follow',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('follower',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='following_links',to='auth.user')),('following',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='follower_links',to='auth.user'))],options={'ordering':['-created_at']}),
        migrations.CreateModel(name='Like',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('post',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='likes',to='social.post')),('user',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='post_likes',to='auth.user'))]),
        migrations.CreateModel(name='Comment',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('text',models.CharField(max_length=600)),('created_at',models.DateTimeField(auto_now_add=True)),('post',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='comments',to='social.post')),('user',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='comments',to='auth.user'))],options={'ordering':['created_at']}),
        migrations.CreateModel(name='StoryLike',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('story',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='likes',to='social.story')),('user',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='story_likes',to='auth.user'))]),
        migrations.CreateModel(name='StoryReply',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('text',models.CharField(max_length=500)),('created_at',models.DateTimeField(auto_now_add=True)),('story',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='replies',to='social.story')),('user',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='story_replies',to='auth.user'))],options={'ordering':['created_at']}),
        migrations.CreateModel(name='StoryView',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('viewed_at',models.DateTimeField(auto_now_add=True)),('story',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='views',to='social.story')),('user',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='story_views',to='auth.user'))]),
        migrations.CreateModel(name='Notification',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('kind',models.CharField(choices=[('like','liked your post'),('comment','commented on your post'),('follow','started following you'),('story_like','liked your story'),('story_reply','replied to your story')],max_length=30)),('text',models.CharField(blank=True,max_length=500)),('created_at',models.DateTimeField(auto_now_add=True)),('is_read',models.BooleanField(default=False)),('actor',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='sent_notifications',to='auth.user')),('post',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.CASCADE,to='social.post')),('recipient',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='notifications',to='auth.user')),('story',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.CASCADE,to='social.story'))],options={'ordering':['-created_at']}),
        migrations.AddConstraint(model_name='follow',constraint=models.UniqueConstraint(fields=('follower','following'),name='unique_follow')),
        migrations.AddConstraint(model_name='like',constraint=models.UniqueConstraint(fields=('user','post'),name='unique_post_like')),
        migrations.AddConstraint(model_name='storylike',constraint=models.UniqueConstraint(fields=('user','story'),name='unique_story_like')),
        migrations.AddConstraint(model_name='storyview',constraint=models.UniqueConstraint(fields=('user','story'),name='unique_story_view')),
    ]
